const preguntasPorEdad = {
  "config": {
    "saveScore": true,
    "shuffleOnRestart": true
  },
  "levels": {
    "preescolar": {
      "name": "Preescolar (3-5 años)",
      "icon": "🧸",
      "questions": [
        {"type": "truefalse", "text": "El cielo es azul", "correct": true},
        {"type": "truefalse", "text": "El pasto es rojo", "correct": false},
        {"type": "truefalse", "text": "El sol sale de día", "correct": true},
        {"type": "truefalse", "text": "La nieve es caliente", "correct": false},
        {"type": "truefalse", "text": "Los peces viven en el agua", "correct": true},
        {"type": "truefalse", "text": "Los pájaros vuelan", "correct": true},
        {"type": "truefalse", "text": "Los perros maúllan", "correct": false},
        {"type": "truefalse", "text": "La luna brilla de noche", "correct": true},
        {"type": "truefalse", "text": "El fuego quema", "correct": true},
        {"type": "truefalse", "text": "El hielo está caliente", "correct": false},
        {"type": "truefalse", "text": "Las manzanas son rojas o verdes", "correct": true},
        {"type": "truefalse", "text": "Los elefantes son pequeños", "correct": false},
        {"type": "truefalse", "text": "El agua moja", "correct": true},
        {"type": "truefalse", "text": "La tierra es redonda", "correct": true},
        {"type": "truefalse", "text": "La noche es de día", "correct": false},
        {"type": "multiple", "text": "¿Cuál es el color de la pelota de fútbol?", "options": ["Azul", "Blanca con negro", "Roja", "Verde"], "correct": "Blanca con negro"},
        {"type": "truefalse", "text": "El portero puede agarrar la pelota con las manos", "correct": true},
        {"type": "multiple", "text": "¿Qué parte del cuerpo usas para patear la pelota?", "options": ["Manos", "Cabeza", "Pies", "Rodillas"], "correct": "Pies"},
        {"type": "truefalse", "text": "Cuando metes un gol, estás feliz", "correct": true},
        {"type": "multiple", "text": "¿Qué animal dice 'muu'?", "options": ["Perro", "Gato", "Vaca", "Pájaro"], "correct": "Vaca"},
        {"type": "truefalse", "text": "El agua está seca", "correct": false},
        {"type": "multiple", "text": "¿De qué color es la camiseta de Brasil?", "options": ["Azul", "Amarilla y verde", "Roja", "Blanca"], "correct": "Amarilla y verde"},
        {"type": "truefalse", "text": "El fútbol se juega con las manos", "correct": false},
        {"type": "multiple", "text": "¿Cuántos jugadores juegan en un equipo de fútbol?", "options": ["5", "8", "11", "15"], "correct": "11"},
        {"type": "truefalse", "text": "La fruta plátano es amarilla", "correct": true},
        {"type": "multiple", "text": "¿Qué forma tiene la pelota de fútbol?", "options": ["Cuadrada", "Triángulo", "Redonda", "Rectángulo"], "correct": "Redonda"},
        {"type": "multiple", "text": "¿Qué animal hace 'guau guau'?", "options": ["Gato", "Perro", "Vaca", "Gallina"], "correct": "Perro"},
        {"type": "truefalse", "text": "El chocolate es dulce", "correct": true},
        {"type": "multiple", "text": "¿Qué color es la nieve?", "options": ["Negro", "Azul", "Blanco", "Rojo"], "correct": "Blanco"},
        {"type": "truefalse", "text": "Las flores huelen rico", "correct": true},
        {"type": "multiple", "text": "¿Qué usas para ver?", "options": ["Oídos", "Ojos", "Nariz", "Boca"], "correct": "Ojos"},
        {"type": "truefalse", "text": "El auto vuela", "correct": false},
        {"type": "multiple", "text": "¿Qué animal tiene trompa larga?", "options": ["Jirafa", "Elefante", "León", "Cebra"], "correct": "Elefante"},
        {"type": "truefalse", "text": "La pizza tiene queso", "correct": true},
        {"type": "multiple", "text": "¿Qué usas para escuchar música?", "options": ["Ojos", "Manos", "Oídos", "Pies"], "correct": "Oídos"},
        {"type": "truefalse", "text": "El sol es de noche", "correct": false},
        {"type": "multiple", "text": "¿Qué animal nada en el agua?", "options": ["Gato", "Perro", "Pez", "Pájaro"], "correct": "Pez"},
        {"type": "truefalse", "text": "La leche es blanca", "correct": true},
        {"type": "multiple", "text": "¿Qué fruta es amarilla por fuera?", "options": ["Manzana", "Plátano", "Uva", "Fresa"], "correct": "Plátano"},
        {"type": "truefalse", "text": "Los coches tienen ruedas", "correct": true},
        {"type": "multiple", "text": "¿Qué animal vuela?", "options": ["Perro", "Gato", "Pájaro", "Pez"], "correct": "Pájaro"},
        {"type": "truefalse", "text": "El hielo es líquido", "correct": false},
        {"type": "multiple", "text": "¿Qué color es el pasto?", "options": ["Azul", "Rojo", "Verde", "Amarillo"], "correct": "Verde"},
        {"type": "truefalse", "text": "Los árboles dan sombra", "correct": true},
        {"type": "multiple", "text": "¿Qué usas para comer sopa?", "options": ["Tenedor", "Cuchara", "Cuchillo", "Palillos"], "correct": "Cuchara"},
        {"type": "truefalse", "text": "La lluvia moja", "correct": true},
        {"type": "multiple", "text": "¿Qué animal dice 'pío pío'?", "options": ["Perro", "Gato", "Pollito", "Vaca"], "correct": "Pollito"},
        {"type": "truefalse", "text": "El fuego quema", "correct": true},
        {"type": "multiple", "text": "¿Qué usas para escribir?", "options": ["Tijeras", "Lápiz", "Pegamento", "Regla"], "correct": "Lápiz"},
        {"type": "truefalse", "text": "Los patos nadan en el agua", "correct": true},
        {"type": "multiple", "text": "¿Qué animal tiene joroba?", "options": ["Caballo", "Camello", "Vaca", "Oveja"], "correct": "Camello"},
        {"type": "truefalse", "text": "La miel es dulce", "correct": true},
        {"type": "multiple", "text": "¿Qué color es el tomate maduro?", "options": ["Verde", "Amarillo", "Rojo", "Morado"], "correct": "Rojo"},
        {"type": "truefalse", "text": "Los aviones vuelan", "correct": true},
        {"type": "multiple", "text": "¿Qué animal vive en el desierto?", "options": ["Pez", "Pingüino", "Camello", "Oso polar"], "correct": "Camello"},
        {"type": "truefalse", "text": "El azúcar es dulce", "correct": true},
        {"type": "multiple", "text": "¿Qué prenda usas en la cabeza?", "options": ["Zapatos", "Gorra", "Pantalón", "Camisa"], "correct": "Gorra"},
        {"type": "truefalse", "text": "Los tiburones son peces", "correct": true},
        {"type": "multiple", "text": "¿Qué color es la naranja?", "options": ["Roja", "Amarilla", "Naranja", "Verde"], "correct": "Naranja"},
        {"type": "truefalse", "text": "El limón es ácido", "correct": true},
        {"type": "multiple", "text": "¿Qué animal tiene caparazón?", "options": ["Conejo", "Tortuga", "Rana", "Serpiente"], "correct": "Tortuga"},
        {"type": "truefalse", "text": "Las estrellas brillan de noche", "correct": true},
        {"type": "multiple", "text": "¿Qué usas para cortar papel?", "options": ["Lápiz", "Tijeras", "Goma", "Regla"], "correct": "Tijeras"},
        {"type": "truefalse", "text": "El caracol es lento", "correct": true},
        {"type": "multiple", "text": "¿Qué animal dice 'croac croac'?", "options": ["Perro", "Gato", "Rana", "Pájaro"], "correct": "Rana"},
        {"type": "truefalse", "text": "La sal es salada", "correct": true},
        {"type": "multiple", "text": "¿Qué usas para dormir?", "options": ["Silla", "Mesa", "Cama", "Sofá"], "correct": "Cama"},
        {"type": "truefalse", "text": "El hielo se derrite con calor", "correct": true},
        {"type": "multiple", "text": "¿Qué animal vuela y es colorido?", "options": ["Mariposa", "Hormiga", "Araña", "Gusano"], "correct": "Mariposa"},
        {"type": "truefalse", "text": "La guitarra es un instrumento musical", "correct": true},
        {"type": "multiple", "text": "¿Qué fruta es roja por dentro con semillas negras?", "options": ["Manzana verde", "Sandía", "Perá", "Naranja"], "correct": "Sandía"},
        {"type": "truefalse", "text": "El osito de peluche es suave", "correct": true},
        {"type": "multiple", "text": "¿Qué animal tiene rayas blancas y negras?", "options": ["León", "Tigre", "Cebra", "Jirafa"], "correct": "Cebra"}
      ]
    },
    "primaria": {
      "name": "Primaria (6-10 años)",
      "icon": "📚",
      "questions": [
        {"type": "truefalse", "text": "Brasil ha ganado 5 Copas del Mundo", "correct": true},
        {"type": "multiple", "text": "¿Qué país fue sede del Mundial 2018?", "options": ["Brasil", "Alemania", "Rusia", "Francia"], "correct": "Rusia"},
        {"type": "truefalse", "text": "Lionel Messi es de España", "correct": false},
        {"type": "multiple", "text": "¿Qué país ganó el Mundial 2022?", "options": ["Francia", "Argentina", "Brasil", "Croacia"], "correct": "Argentina"},
        {"type": "truefalse", "text": "El penal se cobra a 11 metros", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene tres leones en su escudo?", "options": ["Inglaterra", "España", "Francia", "Italia"], "correct": "Inglaterra"},
        {"type": "truefalse", "text": "Cristiano Ronaldo es portugués", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene una hoja de arce en su bandera?", "options": ["EE.UU.", "Canadá", "México", "Australia"], "correct": "Canadá"},
        {"type": "truefalse", "text": "El Mundial se juega cada 4 años", "correct": true},
        {"type": "multiple", "text": "¿Quién es el máximo goleador histórico de los mundiales?", "options": ["Messi", "Cristiano Ronaldo", "Pelé", "Miroslav Klose"], "correct": "Miroslav Klose"},
        {"type": "truefalse", "text": "El árbitro usa tarjetas amarillas y rojas", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el águila en su escudo?", "options": ["México", "Argentina", "Chile", "Perú"], "correct": "México"},
        {"type": "truefalse", "text": "La Copa del Mundo es de oro", "correct": true},
        {"type": "multiple", "text": "¿Qué selección es conocida como 'La Roja'?", "options": ["Chile", "España", "Italia", "Francia"], "correct": "España"},
        {"type": "truefalse", "text": "El VAR se usa en los mundiales", "correct": true},
        {"type": "multiple", "text": "¿Qué país europeo tiene una rosa en su escudo?", "options": ["Francia", "Alemania", "Inglaterra", "Italia"], "correct": "Inglaterra"},
        {"type": "truefalse", "text": "El fútbol femenino tiene su propio Mundial", "correct": true},
        {"type": "multiple", "text": "¿Qué selección usa camiseta naranja?", "options": ["Países Bajos", "Alemania", "Bélgica", "Portugal"], "correct": "Países Bajos"},
        {"type": "truefalse", "text": "El Mundial 2014 fue en Brasil", "correct": true},
        {"type": "multiple", "text": "¿Qué país africano fue sede del Mundial 2010?", "options": ["Egipto", "Marruecos", "Sudáfrica", "Nigeria"], "correct": "Sudáfrica"},
        {"type": "truefalse", "text": "El fuera de juego es una regla del fútbol", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador tiene el apodo 'La Pulga'?", "options": ["Messi", "Maradona", "Pelé", "Mbappé"], "correct": "Messi"},
        {"type": "truefalse", "text": "Japón ha participado en varios mundiales", "correct": true},
        {"type": "multiple", "text": "¿Qué selección sudamericana tiene 4 estrellas en su escudo?", "options": ["Argentina", "Brasil", "Uruguay", "Chile"], "correct": "Uruguay"},
        {"type": "truefalse", "text": "El estadio Maracaná está en Brasil", "correct": true},
        {"type": "multiple", "text": "¿Qué país ganó el Mundial 2014?", "options": ["Alemania", "Argentina", "Brasil", "Holanda"], "correct": "Alemania"},
        {"type": "truefalse", "text": "Kylian Mbappé es francés", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Cafeteros'?", "options": ["Colombia", "Venezuela", "Ecuador", "Perú"], "correct": "Colombia"},
        {"type": "truefalse", "text": "El Mundial 2002 fue en Corea y Japón", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el Sol en su bandera?", "options": ["Argentina", "Uruguay", "Brasil", "Chile"], "correct": "Argentina"},
        {"type": "truefalse", "text": "El trofeo de la Copa del Mundo se llama Copa Jules Rimet", "correct": false},
        {"type": "multiple", "text": "¿Qué selección es conocida como 'La Celeste'?", "options": ["Argentina", "Brasil", "Uruguay", "Paraguay"], "correct": "Uruguay"},
        {"type": "truefalse", "text": "Pelé jugó en Brasil", "correct": true},
        {"type": "multiple", "text": "¿Qué país fue sede del Mundial 2006?", "options": ["Francia", "Alemania", "Italia", "Inglaterra"], "correct": "Alemania"},
        {"type": "truefalse", "text": "La mascota de Brasil 2014 fue Fuleco", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Leones Indomables'?", "options": ["Camerún", "Senegal", "Ghana", "Nigeria"], "correct": "Camerún"},
        {"type": "truefalse", "text": "El país más ganador de mundiales es Brasil", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador tiene el récord de más partidos en mundiales?", "options": ["Messi", "Maradona", "Lothar Matthäus", "Ronaldo"], "correct": "Lothar Matthäus"},
        {"type": "truefalse", "text": "El árbitro puede expulsar jugadores", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene una estrella en su escudo por cada mundial ganado?", "options": ["Argentina", "Brasil", "Alemania", "Todas las campeonas"], "correct": "Todas las campeonas"},
        {"type": "truefalse", "text": "El Mundial 1930 fue en Uruguay", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el apodo 'La Albirroja'?", "options": ["Paraguay", "Perú", "Bolivia", "Chile"], "correct": "Paraguay"},
        {"type": "truefalse", "text": "Los jugadores usan espinilleras", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Ticos'?", "options": ["Costa Rica", "Honduras", "Panamá", "El Salvador"], "correct": "Costa Rica"},
        {"type": "truefalse", "text": "El balón oficial del Mundial 2022 fue Al Rihla", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador tiene el récord de más goles en un solo mundial?", "options": ["Pelé", "Messi", "Just Fontaine", "Mbappé"], "correct": "Just Fontaine"},
        {"type": "truefalse", "text": "Holanda nunca ha ganado un mundial", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el apodo 'La Verde'?", "options": ["México", "Brasil", "Italia", "Irlanda"], "correct": "México"},
        {"type": "truefalse", "text": "El fútbol es el deporte más popular del mundo", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Vikingos'?", "options": ["Suecia", "Noruega", "Dinamarca", "Islandia"], "correct": "Suecia"}
      ]
    },
    "bachillerato": {
      "name": "Bachillerato (11-17 años)",
      "icon": "🎓",
      "questions": [
        {"type": "truefalse", "text": "Uruguay ganó el primer Mundial en 1930", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador ha ganado más Balones de Oro?", "options": ["Messi", "Cristiano Ronaldo", "Pelé", "Maradona"], "correct": "Messi"},
        {"type": "truefalse", "text": "El Maracanazo fue la derrota de Brasil en 1950", "correct": true},
        {"type": "multiple", "text": "¿Qué país ha perdido más finales del Mundial?", "options": ["Alemania", "Argentina", "Italia", "Holanda"], "correct": "Alemania"},
        {"type": "truefalse", "text": "Pelé ganó su primer mundial a los 17 años", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el récord de más mundiales ganados?", "options": ["Alemania", "Italia", "Argentina", "Brasil"], "correct": "Brasil"},
        {"type": "truefalse", "text": "Croacia fue subcampeón en 2018", "correct": true},
        {"type": "multiple", "text": "¿Qué árbitro dirigió la final de 2006?", "options": ["Collina", "Pitana", "Webb", "Irmatov"], "correct": "Collina"},
        {"type": "truefalse", "text": "El Balón de Oro se da al mejor jugador del torneo", "correct": true},
        {"type": "multiple", "text": "¿Cuántos equipos participaron en el Mundial 2022?", "options": ["24", "32", "36", "48"], "correct": "32"},
        {"type": "truefalse", "text": "La Bota de Oro es para el máximo goleador", "correct": true},
        {"type": "multiple", "text": "¿Qué país asiático fue sede del Mundial 2002 junto a Japón?", "options": ["China", "Corea del Sur", "Catar", "Arabia Saudita"], "correct": "Corea del Sur"},
        {"type": "truefalse", "text": "Zinedine Zidane fue campeón en 1998", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Cafeteros'?", "options": ["Colombia", "Venezuela", "Ecuador", "Perú"], "correct": "Colombia"},
        {"type": "truefalse", "text": "El Mundial 2026 se jugará en 3 países", "correct": true},
        {"type": "multiple", "text": "¿Qué país eliminó a Alemania en 2022 en fase de grupos?", "options": ["España", "Costa Rica", "Japón", "Marruecos"], "correct": "Japón"},
        {"type": "truefalse", "text": "Mbappé anotó un triplete en la final de 2022", "correct": true},
        {"type": "multiple", "text": "¿Qué arquero tiene el récord de vallas invictas en mundiales?", "options": ["Neuer", "Buffon", "Casillas", "Zoff"], "correct": "Casillas"},
        {"type": "truefalse", "text": "El 'Golden Glove' es para el mejor arquero", "correct": true},
        {"type": "multiple", "text": "¿Qué selección africana llegó a semifinales en 2022?", "options": ["Senegal", "Marruecos", "Ghana", "Camerún"], "correct": "Marruecos"},
        {"type": "truefalse", "text": "El himno nacional se canta antes de cada partido", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el apodo 'Los Ticos'?", "options": ["Costa Rica", "Honduras", "Panamá", "Nicaragua"], "correct": "Costa Rica"},
        {"type": "truefalse", "text": "El trofeo de la Copa del Mundo es de oro macizo", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador tiene el récord de más partidos en mundiales?", "options": ["Messi", "Maradona", "Matthäus", "Ronaldo"], "correct": "Matthäus"},
        {"type": "truefalse", "text": "Brasil es el único país que ha jugado todos los mundiales", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'La Albiceleste'?", "options": ["Argentina", "Uruguay", "Paraguay", "Chile"], "correct": "Argentina"},
        {"type": "truefalse", "text": "El Mundial 2030 será el centenario", "correct": true},
        {"type": "multiple", "text": "¿Qué arquero atajó más penales en tandas?", "options": ["Goycochea", "Neuer", "Buffon", "Schmeichel"], "correct": "Goycochea"},
        {"type": "truefalse", "text": "Rusia fue sede del Mundial 2018", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Leones Indomables'?", "options": ["Camerún", "Senegal", "Ghana", "Nigeria"], "correct": "Camerún"},
        {"type": "truefalse", "text": "El VAR se implementó por primera vez en 2018", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el récord de más goles en un solo mundial?", "options": ["Hungría 1954", "Brasil 1970", "Alemania 2014", "Francia 1998"], "correct": "Hungría 1954"},
        {"type": "truefalse", "text": "La mascota del Mundial 2022 se llamaba La'eeb", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador tiene el récord de más asistencias en mundiales?", "options": ["Messi", "Pelé", "Maradona", "Klose"], "correct": "Messi"},
        {"type": "truefalse", "text": "Catar 2022 fue el primer mundial en invierno", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'La Furia Roja'?", "options": ["España", "Bélgica", "Holanda", "Portugal"], "correct": "España"},
        {"type": "truefalse", "text": "Inglaterra ganó el mundial en 1966", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador es conocido como 'El Rey Pelé'?", "options": ["Pelé", "Maradona", "Cruyff", "Beckenbauer"], "correct": "Pelé"},
        {"type": "truefalse", "text": "Francia ganó el mundial 2018", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Halcones'?", "options": ["México", "Nigeria", "Argelia", "Egipto"], "correct": "Nigeria"},
        {"type": "truefalse", "text": "El estadio Wembley está en Inglaterra", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador metió la 'Mano de Dios'?", "options": ["Messi", "Maradona", "Pelé", "Zidane"], "correct": "Maradona"},
        {"type": "truefalse", "text": "El gol más rápido en un mundial es de 11 segundos", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Mapaches'?", "options": ["Costa Rica", "Honduras", "Panamá", "Guatemala"], "correct": "Costa Rica"},
        {"type": "truefalse", "text": "Alemania ganó el mundial 2014", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el apodo 'La Tri'?", "options": ["Ecuador", "Colombia", "Venezuela", "Perú"], "correct": "Ecuador"},
        {"type": "truefalse", "text": "El mundial 1950 no tuvo final, fue liga final", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Canaleros'?", "options": ["Costa Rica", "Honduras", "Panamá", "Nicaragua"], "correct": "Panamá"},
        {"type": "truefalse", "text": "El mejor jugador del mundial 2014 fue Messi", "correct": true},
        {"type": "multiple", "text": "¿Qué país fue sede del mundial 1978?", "options": ["Argentina", "Perú", "Chile", "Uruguay"], "correct": "Argentina"},
        {"type": "truefalse", "text": "El balón Tango fue usado en 1978", "correct": false},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Charrúas'?", "options": ["Uruguay", "Argentina", "Paraguay", "Chile"], "correct": "Uruguay"},
        {"type": "truefalse", "text": "Zidane fue expulsado en su última final", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador anotó el gol del siglo?", "options": ["Messi", "Maradona", "Ronaldo", "Ronaldinho"], "correct": "Maradona"},
        {"type": "truefalse", "text": "El mundial 1998 fue en Francia", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el apodo 'Los Qatíes'?", "options": ["Catar", "Emiratos", "Arabia", "Omán"], "correct": "Catar"},
        {"type": "truefalse", "text": "El récord de goles en un mundial es 13 de Fontaine", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Samuráis Azules'?", "options": ["Japón", "Corea", "China", "Taiwán"], "correct": "Japón"},
        {"type": "truefalse", "text": "El himno de la Champions no se usa en mundiales", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Las Águilas'?", "options": ["México", "Perú", "Colombia", "Bolivia"], "correct": "México"},
        {"type": "truefalse", "text": "El mundial 1966 fue en Inglaterra", "correct": true},
        {"type": "multiple", "text": "¿Qué jugador anotó un hat-trick en final de 2022?", "options": ["Messi", "Mbappé", "Di María", "Giroud"], "correct": "Mbappé"},
        {"type": "truefalse", "text": "Países Bajos tiene 3 subcampeonatos", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Bravos'?", "options": ["Paraguay", "Bolivia", "Ecuador", "Venezuela"], "correct": "Bolivia"},
        {"type": "truefalse", "text": "El mundial 1994 fue en Estados Unidos", "correct": true},
        {"type": "multiple", "text": "¿Qué país tiene el apodo 'Los Lusitanos'?", "options": ["Portugal", "España", "Francia", "Italia"], "correct": "Portugal"},
        {"type": "truefalse", "text": "Croacia fue 3er lugar en 1998", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Las Chicas de Rojo' (femenino)?", "options": ["España", "Francia", "Italia", "Inglaterra"], "correct": "España"},
        {"type": "truefalse", "text": "El mundial 1958 fue en Suecia", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Tucanes'?", "options": ["Brasil", "Colombia", "Perú", "Venezuela"], "correct": "Brasil"},
        {"type": "truefalse", "text": "El único portero Balón de Oro fue Lev Yashin", "correct": true},
        {"type": "multiple", "text": "¿Qué selección tiene el apodo 'Los Dragones Rojos'?", "options": ["Gales", "Escocia", "Irlanda", "Inglaterra"], "correct": "Gales"},
        {"type": "truefalse", "text": "El mundial 1970 fue en México", "correct": true}
      ]
    }
  }
};

console.log('✅ preguntas.js - VERSIÓN MÁXIMA cargada');
console.log('📊 Total de preguntas:', {
  preescolar: preguntasPorEdad.levels.preescolar.questions.length,
  primaria: preguntasPorEdad.levels.primaria.questions.length,
  bachillerato: preguntasPorEdad.levels.bachillerato.questions.length
});